//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public string MADANHGIA { get; set; }
        public string MASP { get; set; }
        public string MAKH { get; set; }
        public Nullable<byte> SOSAODANHGIA { get; set; }
        public Nullable<System.DateTime> NGAYDANHGIA { get; set; }
        public string CHITIETDANHGIA { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
