//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAMGIA
    {
        public string MAGIAMGIA { get; set; }
        public string MASP { get; set; }
        public Nullable<byte> PHANTRAMGIAM { get; set; }
        public Nullable<System.DateTime> NGAYAPDUNG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
