//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_DONHANG = new HashSet<CHITIET_DONHANG>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.GIAMGIAs = new HashSet<GIAMGIA>();
        }
    
        public string MASP { get; set; }
        public string MANHOM { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> GIAGIAM { get; set; }
        public string MOTA { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public string LINK_HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGIA> GIAMGIAs { get; set; }
        public virtual NHOMSANPHAM NHOMSANPHAM { get; set; }
    }
}
